Análise Covid

In [1]:
import pandas as pd
df = pd.read_csv('data/covid19_statistics')

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       237 non-null    int64
 1   continent        236 non-null    str
 2   country          237 non-null    str
 3   cases.active     190 non-null    float64
 4   cases.critical   59 non-null     float64
 5   cases.recovered  189 non-null    float64
 6   cases.total      237 non-null    int64
 7   deaths.total     232 non-null    float64
 8   population(k)    229 non-null    float64
 9   test.total (k)   213 non-null    float64
 10  date             237 non-null    str
 11  time_hms         237 non-null    str
dtypes: float64(6), int64(2), str(4)
memory usage: 22.3 KB

In [3]:
df.head()

,Unnamed: 0,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
0,0,Asia,China,118977.0,NaN,379053.0,503302,5272.0,1448471.400,160000.000,2026-01-22,05:00:13
1,1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
2,2,South-America,Falkland-Islands,0.0,NaN,1930.0,1930,NaN,3.539,8.632,2026-01-22,05:00:12
3,3,North-America,Montserrat,19.0,NaN,1376.0,1403,8.0,4.965,17.762,2026-01-22,05:00:12
4,4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12

In [4]:
df.describe()

,Unnamed: 0,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k)
count,237.000000,1.900000e+02,59.000000,1.890000e+02,2.370000e+02,2.320000e+02,2.290000e+02,2.130000e+02
mean,118.000000,2.650658e+05,1228.220339,1.011538e+07,8.920932e+06,9.065528e+04,3.469404e+04,3.298829e+04
std,68.560193,1.928390e+06,5046.844152,5.569789e+07,5.203699e+07,5.174256e+05,1.386374e+05,1.198779e+05
min,0.000000,0.000000e+00,1.000000,2.000000e+00,1.000000e+01,1.000000e+00,7.990000e-01,7.850000e+00
25%,59.000000,4.725000e+01,4.000000,2.310200e+04,2.767300e+04,2.272500e+02,4.454310e+02,3.478150e+02
50%,118.000000,6.675000e+02,16.000000,2.414860e+05,2.337310e+05,2.628000e+03,5.797805e+03,2.226216e+03
75%,177.000000,8.080250e+03,67.500000,2.152155e+06,1.581936e+06,1.821450e+04,2.210284e+04,1.346373e+04
max,236.000000,2.212340e+07,34794.000000,6.756198e+08,7.047539e+08,7.010681e+06,1.448471e+06,1.186852e+06

In [5]:
df.isnull().sum()

Unnamed: 0           0
continent            1
country              0
cases.active        47
cases.critical     178
cases.recovered     48
cases.total          0
deaths.total         5
population(k)        8
test.total (k)      24
date                 0
time_hms             0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.shape

(237, 12)

In [8]:
df["country"].nunique()

237

In [9]:
(df["cases.total"]< 0).sum()

np.int64(0)

In [10]:
(df["deaths.total"]< 0).sum()

np.int64(0)

In [11]:
(df["population(k)"]< 0).sum()

np.int64(0)

In [12]:
(df["cases.total"] < 0).sum()

np.int64(0)

In [13]:
(df["deaths.total"] > df["cases.total"]).sum()

np.int64(0)

In [14]:
(df["cases.recovered"] > df["cases.total"]).sum()

np.int64(0)

In [15]:
(df["cases.active"] > df["cases.total"]).sum()

np.int64(0)

In [16]:
(df["cases.critical"] > df["cases.total"]).sum()

np.int64(0)

In [17]:
df[df.isna().any(axis=1)]

,Unnamed: 0,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
0,0,Asia,China,118977.0,NaN,379053.0,503302,5272.0,1448471.400,160000.000,2026-01-22,05:00:13
1,1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
2,2,South-America,Falkland-Islands,0.0,NaN,1930.0,1930,NaN,3.539,8.632,2026-01-22,05:00:12
3,3,North-America,Montserrat,19.0,NaN,1376.0,1403,8.0,4.965,17.762,2026-01-22,05:00:12
4,4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
...,...,...,...,...,...,...,...,...,...,...,...,...
231,231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
235,235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

In [18]:
df[df["population(k)"].isna()]

,Unnamed: 0,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
4,4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
229,229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
235,235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

In [19]:
df[df["test.total (k)"].isna()]

,Unnamed: 0,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
1,1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
4,4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
5,5,Europe,Vatican-City,0.0,NaN,29.0,29,NaN,0.799,NaN,2026-01-22,05:00:12
6,6,Africa,Western-Sahara,0.0,NaN,9.0,10,1.0,626.161,NaN,2026-01-22,05:00:12
12,12,Oceania,Tokelau,80.0,NaN,NaN,80,NaN,1.378,NaN,2026-01-22,05:00:12
13,13,Oceania,Kiribati,2358.0,3.0,2703.0,5085,24.0,123.419,NaN,2026-01-22,05:00:12
22,22,Oceania,Tuvalu,NaN,NaN,NaN,2943,1.0,12.066,NaN,2026-01-22,05:00:12
23,23,Oceania,Niue,3.0,NaN,1056.0,1059,NaN,1.622,NaN,2026-01-22,05:00:12
24,24,Asia,Tajikistan,397.0,NaN,17264.0,17786,125.0,9957.464,NaN,2026-01-22,05:00:11
33,33,Africa,Comoros,9.0,NaN,8939.0,9109,161.0,907.419,NaN,2026-01-22,05:00:11
40,40,Oceania,Marshall-Islands,0.0,NaN,16121.0,16138,17.0,60.057,NaN,2026-01-22,05:00:11
50,50,North-America,Nicaragua,14041.0,NaN,4225.0,18491,225.0,6779.100,NaN,2026-01-22,05:00:10
65,65,Oceania,Solomon-Islands,NaN,NaN,NaN,25954,199.0,721.159,NaN,2026-01-22,05:00:10
84,84,Africa,Seychelles,0.0,NaN,51048.0,51220,172.0,99.426,NaN,2026-01-22,05:00:09
88,88,Africa,Tanzania,NaN,NaN,NaN,43223,846.0,63298.550,NaN,2026-01-22,05:00:09
114,114,Oceania,French-Polynesia,NaN,NaN,NaN,79254,650.0,284.164,NaN,2026-01-22,05:00:08
183,183,Asia,DPRK,0.0,NaN,4772739.0,4772813,74.0,25990.679,NaN,2026-01-22,05:00:04
229,229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
235,235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

In [20]:
df.groupby("country").size().sort_values(ascending=False).head()

country
Afghanistan    1
Africa         1
Albania        1
Algeria        1
All            1
dtype: int64

In [21]:
df[df["country"].str.contains("Africa|Europe|Asia|America|Oceania|All", na=False)]

,Unnamed: 0,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
184,184,Africa,South-Africa,61362.0,192.0,3912506.0,4076463,102595.0,60756.135,26795.09,2026-01-22,05:00:04
229,229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
235,235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

Investigando o REGISTRO All

In [22]:
df = df.drop(columns=["Unnamed: 0"])

In [23]:
df.loc[0:234, "cases.total"].sum()

np.int64(1297686968)

In [24]:
df.loc[2, "cases.total"].sum()

np.int64(1930)

In [25]:
all = df.loc[df["country"] == "All"]

In [26]:
all

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

In [27]:
all_cases = df.loc[
    df["country"]  == "All",
       "cases.total"
].iloc[0]

all_cases

np.int64(704753890)

In [28]:
df.loc[df["country"] != "All", "cases.total"].sum()

np.int64(1409507050)

In [29]:
all[[
    "cases.active",
    "deaths.total",
    "cases.recovered"
]].iloc[0].sum()

np.float64(704753890.0)

In [30]:
all_df = df[df["continent"] == "All"].copy()

In [31]:
df_clean = df[df["continent"] != "All"].copy()

In [32]:
df.shape

(237, 11)

In [33]:
df_clean.shape

(236, 11)

In [34]:
all_df.shape

(1, 11)

In [35]:
df_clean["date"].unique()

<StringArray>
['2026-01-22']
Length: 1, dtype: str

In [36]:
df_clean["date"].nunique()

1

In [37]:
df_clean[df_clean["time_hms"].str.contains("05:00:02", na=False)]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
236,North-America,USA,786167.0,940.0,109814428.0,111820082,1219487.0,334805.269,1186851.502,2026-01-22,05:00:02

In [38]:
df_clean.loc[
    df_clean["time_hms"].str.contains("05:00:02", na=False),
    "cases.total"
].sum()

np.int64(816573251)

Resumo da seção: Durante a investigação dos dados foi identificado um registro denominado All. Testes mostraram que seu valor não corresponde ao total mundial nem à soma de todos os países. Entretanto, ao somar os registros que apresentavam inconsistências de localização para o mesmo instante de coleta, o resultado obtido foi muito próximo ao valor de All. Isso sugere que esse registro representa um agregado desses registros inconsistentes, razão pela qual foi separado da análise principal.

In [39]:
df_clean.loc[df_clean["population(k)"].idxmax()]

continent                Asia
country                 China
cases.active         118977.0
cases.critical            NaN
cases.recovered      379053.0
cases.total            503302
deaths.total           5272.0
population(k)       1448471.4
test.total (k)       160000.0
date               2026-01-22
time_hms             05:00:13
Name: 0, dtype: object

In [40]:
df_clean.loc[df_clean["cases.total"].idxmax()]

continent               Europe
country                 Europe
cases.active         2550270.0
cases.critical          4453.0
cases.recovered    248754104.0
cases.total          253406198
deaths.total         2101824.0
population(k)              NaN
test.total (k)             NaN
date                2026-01-22
time_hms              05:00:02
Name: 231, dtype: object

In [41]:
df_clean.loc[df_clean["deaths.total"].idxmax()]

continent               Europe
country                 Europe
cases.active         2550270.0
cases.critical          4453.0
cases.recovered    248754104.0
cases.total          253406198
deaths.total         2101824.0
population(k)              NaN
test.total (k)             NaN
date                2026-01-22
time_hms              05:00:02
Name: 231, dtype: object

Registros com localzação inconsistentes

In [42]:
df_clean[df_clean["country"].str.contains("Africa|Europe|Asia|America|Oceania", na=False)]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
184,Africa,South-Africa,61362.0,192.0,3912506.0,4076463,102595.0,60756.135,26795.09,2026-01-22,05:00:04
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02

Foram identificados sete registros com inconsistências de localização. Seis deles apresentavam informações de país inconsistentes, além da ausência dos valores de população e total de testes. Como não foi possível recuperar essas informações de forma confiável e a unidade de análise deste projeto é o país, esses seis registros foram removidos do conjunto de dados utilizado na análise exploratória.

In [43]:
df_clean[df_clean["population(k)"].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02

In [44]:
df_clean[df_clean["test.total (k)"].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
5,Europe,Vatican-City,0.0,NaN,29.0,29,NaN,0.799,NaN,2026-01-22,05:00:12
6,Africa,Western-Sahara,0.0,NaN,9.0,10,1.0,626.161,NaN,2026-01-22,05:00:12
12,Oceania,Tokelau,80.0,NaN,NaN,80,NaN,1.378,NaN,2026-01-22,05:00:12
13,Oceania,Kiribati,2358.0,3.0,2703.0,5085,24.0,123.419,NaN,2026-01-22,05:00:12
22,Oceania,Tuvalu,NaN,NaN,NaN,2943,1.0,12.066,NaN,2026-01-22,05:00:12
23,Oceania,Niue,3.0,NaN,1056.0,1059,NaN,1.622,NaN,2026-01-22,05:00:12
24,Asia,Tajikistan,397.0,NaN,17264.0,17786,125.0,9957.464,NaN,2026-01-22,05:00:11
33,Africa,Comoros,9.0,NaN,8939.0,9109,161.0,907.419,NaN,2026-01-22,05:00:11
40,Oceania,Marshall-Islands,0.0,NaN,16121.0,16138,17.0,60.057,NaN,2026-01-22,05:00:11
50,North-America,Nicaragua,14041.0,NaN,4225.0,18491,225.0,6779.100,NaN,2026-01-22,05:00:10
65,Oceania,Solomon-Islands,NaN,NaN,NaN,25954,199.0,721.159,NaN,2026-01-22,05:00:10
84,Africa,Seychelles,0.0,NaN,51048.0,51220,172.0,99.426,NaN,2026-01-22,05:00:09
88,Africa,Tanzania,NaN,NaN,NaN,43223,846.0,63298.550,NaN,2026-01-22,05:00:09
114,Oceania,French-Polynesia,NaN,NaN,NaN,79254,650.0,284.164,NaN,2026-01-22,05:00:08
183,Asia,DPRK,0.0,NaN,4772739.0,4772813,74.0,25990.679,NaN,2026-01-22,05:00:04
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02

In [45]:
df_clean[df_clean["continent"].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12

In [46]:
df_clean[df_clean["country"].isna()]

Empty DataFrame
Columns: [continent, country, cases.active, cases.critical, cases.recovered, cases.total, deaths.total, population(k), test.total (k), date, time_hms]
Index: []

Foi identificado um registro referente ao Diamond Princess, um navio de cruzeiro, e não a um país ou território. Como a unidade de análise deste projeto são países, esse registro foi removido do conjunto de dados para manter a consistência das comparações realizadas

Investigando Nulos

In [47]:
(df.isnull().sum() / len(df)) * 100

continent           0.421941
country             0.000000
cases.active       19.831224
cases.critical     75.105485
cases.recovered    20.253165
cases.total         0.000000
deaths.total        2.109705
population(k)       3.375527
test.total (k)     10.126582
date                0.000000
time_hms            0.000000
dtype: float64

In [48]:
null_analysis = pd.DataFrame({
    'nulos': df.isnull().sum(),
    'percentual_nulos': (df.isnull().sum() / len(df)) * 100
})

null_analysis

                 nulos  percentual_nulos
continent            1          0.421941
country              0          0.000000
cases.active        47         19.831224
cases.critical     178         75.105485
cases.recovered     48         20.253165
cases.total          0          0.000000
deaths.total         5          2.109705
population(k)        8          3.375527
test.total (k)      24         10.126582
date                 0          0.000000
time_hms             0          0.000000

In [49]:
df[df['deaths.total'].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
2,South-America,Falkland-Islands,0.0,NaN,1930.0,1930,NaN,3.539,8.632,2026-01-22,05:00:12
5,Europe,Vatican-City,0.0,NaN,29.0,29,NaN,0.799,NaN,2026-01-22,05:00:12
12,Oceania,Tokelau,80.0,NaN,NaN,80,NaN,1.378,NaN,2026-01-22,05:00:12
23,Oceania,Niue,3.0,NaN,1056.0,1059,NaN,1.622,NaN,2026-01-22,05:00:12

In [50]:
df.loc[
    df['deaths.total'].isna(),
    ['country', 'cases.total', 'cases.recovered', 'cases.active', 'deaths.total']
]

             country  cases.total  cases.recovered  cases.active  deaths.total
1       Saint-Helena         2166              2.0        2164.0           NaN
2   Falkland-Islands         1930           1930.0           0.0           NaN
5       Vatican-City           29             29.0           0.0           NaN
12           Tokelau           80              NaN          80.0           NaN
23              Niue         1059           1056.0           3.0           NaN

In [51]:
df.loc[
    (df['deaths.total'].isna()) & 
    (df['cases.active'] == 0),
    ['country', 'cases.total', 'cases.recovered', 'cases.active', 'deaths.total']
]

            country  cases.total  cases.recovered  cases.active  deaths.total
2  Falkland-Islands         1930           1930.0           0.0           NaN
5      Vatican-City           29             29.0           0.0           NaN

In [52]:
df.loc[
    (df['deaths.total'].isna()) & 
    (df['population(k)'] == 0.799)
]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
5,Europe,Vatican-City,0.0,NaN,29.0,29,NaN,0.799,NaN,2026-01-22,05:00:12

Vaticano — inconsistência populacional

O registro apresenta population(k) = 0.799, equivalente a aproximadamente 799 habitantes. Para verificar a plausibilidade desse valor, foram consultadas fontes externas sobre a população do Vaticano em 2026. Estimativas para 2026 indicam aproximadamente 506 habitantes, enquanto a área territorial oficial do Estado é de 0,44 km².

Embora o valor registrado não seja incompatível em ordem de grandeza com a população do Vaticano, ele não corresponde à referência populacional encontrada para o período analisado. Como a população é uma variável fundamental para análises normalizadas por população e o registro representa uma entidade com características demográficas extremamente particulares, optou-se por excluí-lo do dataset utilizado na análise

In [53]:
pd.crosstab(
    df['deaths.total'].isna(),
    df['cases.critical'].isna()
)

cases.critical  False  True
deaths.total
False              59    173
True                0      5

Nos registros 1, 2, 12 e 23, os valores ausentes de deaths.total foram tratados como zero, pois a relação entre casos totais, recuperados e ativos permite inferir que não havia casos restantes atribuíveis a óbitos.

In [54]:
df_clean.loc[
    df['country'].isin(['Saint-Helena','Falkland-Islands', 'Tokelau', 'Niue']),
    ['country', 'deaths.total']
]

             country  deaths.total
1       Saint-Helena           NaN
2   Falkland-Islands           NaN
12           Tokelau           NaN
23              Niue           NaN

In [55]:
df[df['population(k)'].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
235,All,All,22123398.0,34794.0,675619811.0,704753890,7010681.0,NaN,NaN,2026-01-22,05:00:02

In [56]:
df_clean.loc[
    df_clean['population(k)'].isna(),
    ['country', 'continent', 'cases.total', 'deaths.total',
     'cases.active', 'cases.recovered', 'test.total (k)']
]

,country,continent,cases.total,deaths.total,cases.active,cases.recovered,test.total (k)
4,Diamond-Princess,NaN,712,13.0,0.0,699.0,NaN
229,North-America,North-America,131889132,1695941.0,2528062.0,127665129.0,NaN
230,Asia,Asia,221500265,1553662.0,14273512.0,205673091.0,NaN
231,Europe,Europe,253406198,2101824.0,2550270.0,248754104.0,NaN
232,South-America,South-America,70200879,1367332.0,2149962.0,66683585.0,NaN
233,Oceania,Oceania,14895771,33015.0,110368.0,14752388.0,NaN
234,Africa,Africa,12860924,258892.0,511224.0,12090808.0,NaN

Durante a investigação dos valores ausentes em population(k), foi identificado um registro adicional com inconsistência geográfica (country = Africa e continent = Africa). Como Africa representa um continente e não um país, o registro foi removido de df_clean, seguindo o mesmo critério aplicado anteriormente aos registros com localização inconsistente.

In [57]:
df_clean[df_clean["population(k)"].isna()]

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
229,North-America,North-America,2528062.0,6095.0,127665129.0,131889132,1695941.0,NaN,NaN,2026-01-22,05:00:02
230,Asia,Asia,14273512.0,14733.0,205673091.0,221500265,1553662.0,NaN,NaN,2026-01-22,05:00:02
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02

In [58]:
df_clean.loc[
    df_clean['test.total (k)'].isna(),
    ['country', 'continent', 'cases.total', 'cases.active',
     'cases.recovered', 'deaths.total', 'population(k)']
]

,country,continent,cases.total,cases.active,cases.recovered,deaths.total,population(k)
1,Saint-Helena,Africa,2166,2164.0,2.0,NaN,6.115
4,Diamond-Princess,NaN,712,0.0,699.0,13.0,NaN
5,Vatican-City,Europe,29,0.0,29.0,NaN,0.799
6,Western-Sahara,Africa,10,0.0,9.0,1.0,626.161
12,Tokelau,Oceania,80,80.0,NaN,NaN,1.378
13,Kiribati,Oceania,5085,2358.0,2703.0,24.0,123.419
22,Tuvalu,Oceania,2943,NaN,NaN,1.0,12.066
23,Niue,Oceania,1059,3.0,1056.0,NaN,1.622
24,Tajikistan,Asia,17786,397.0,17264.0,125.0,9957.464
33,Comoros,Africa,9109,9.0,8939.0,161.0,907.419
40,Marshall-Islands,Oceania,16138,0.0,16121.0,17.0,60.057
50,Nicaragua,North-America,18491,14041.0,4225.0,225.0,6779.100
65,Solomon-Islands,Oceania,25954,NaN,NaN,199.0,721.159
84,Seychelles,Africa,51220,0.0,51048.0,172.0,99.426
88,Tanzania,Africa,43223,NaN,NaN,846.0,63298.550
114,French-Polynesia,Oceania,79254,NaN,NaN,650.0,284.164
183,DPRK,Asia,4772813,0.0,4772739.0,74.0,25990.679
229,North-America,North-America,131889132,2528062.0,127665129.0,1695941.0,NaN
230,Asia,Asia,221500265,14273512.0,205673091.0,1553662.0,NaN
231,Europe,Europe,253406198,2550270.0,248754104.0,2101824.0,NaN
232,South-America,South-America,70200879,2149962.0,66683585.0,1367332.0,NaN
233,Oceania,Oceania,14895771,110368.0,14752388.0,33015.0,NaN
234,Africa,Africa,12860924,511224.0,12090808.0,258892.0,NaN

In [59]:
df_clean.loc[
    df_clean['test.total (k)'].isna(),
    ['country', 'continent', 'cases.total',
     'cases.active', 'cases.recovered',
     'deaths.total', 'population(k)', 'test.total (k)']
]

,country,continent,cases.total,cases.active,cases.recovered,deaths.total,population(k),test.total (k)
1,Saint-Helena,Africa,2166,2164.0,2.0,NaN,6.115,NaN
4,Diamond-Princess,NaN,712,0.0,699.0,13.0,NaN,NaN
5,Vatican-City,Europe,29,0.0,29.0,NaN,0.799,NaN
6,Western-Sahara,Africa,10,0.0,9.0,1.0,626.161,NaN
12,Tokelau,Oceania,80,80.0,NaN,NaN,1.378,NaN
13,Kiribati,Oceania,5085,2358.0,2703.0,24.0,123.419,NaN
22,Tuvalu,Oceania,2943,NaN,NaN,1.0,12.066,NaN
23,Niue,Oceania,1059,3.0,1056.0,NaN,1.622,NaN
24,Tajikistan,Asia,17786,397.0,17264.0,125.0,9957.464,NaN
33,Comoros,Africa,9109,9.0,8939.0,161.0,907.419,NaN
40,Marshall-Islands,Oceania,16138,0.0,16121.0,17.0,60.057,NaN
50,Nicaragua,North-America,18491,14041.0,4225.0,225.0,6779.100,NaN
65,Solomon-Islands,Oceania,25954,NaN,NaN,199.0,721.159,NaN
84,Seychelles,Africa,51220,0.0,51048.0,172.0,99.426,NaN
88,Tanzania,Africa,43223,NaN,NaN,846.0,63298.550,NaN
114,French-Polynesia,Oceania,79254,NaN,NaN,650.0,284.164,NaN
183,DPRK,Asia,4772813,0.0,4772739.0,74.0,25990.679,NaN
229,North-America,North-America,131889132,2528062.0,127665129.0,1695941.0,NaN,NaN
230,Asia,Asia,221500265,14273512.0,205673091.0,1553662.0,NaN,NaN
231,Europe,Europe,253406198,2550270.0,248754104.0,2101824.0,NaN,NaN
232,South-America,South-America,70200879,2149962.0,66683585.0,1367332.0,NaN,NaN
233,Oceania,Oceania,14895771,110368.0,14752388.0,33015.0,NaN,NaN
234,Africa,Africa,12860924,511224.0,12090808.0,258892.0,NaN,NaN

In [60]:
df_clean.loc[
    df_clean.index.isin([22, 88, 114]),
    ['country', 'continent', 'cases.total',
     'cases.active', 'cases.recovered',
     'deaths.total', 'population(k)', 'test.total (k)']
]

,country,continent,cases.total,cases.active,cases.recovered,deaths.total,population(k),test.total (k)
22,Tuvalu,Oceania,2943,NaN,NaN,1.0,12.066,NaN
88,Tanzania,Africa,43223,NaN,NaN,846.0,63298.550,NaN
114,French-Polynesia,Oceania,79254,NaN,NaN,650.0,284.164,NaN

Registros 22, 88 e 114: apresentam valores ausentes em cases.active, cases.recovered e test.total (k). Entretanto, possuem informações completas para continent, country, cases.total, deaths.total e population(k). Como essas variáveis são suficientes para responder aos três objetivos definidos para o projeto, os registros foram mantidos no dataset, preservando os valores ausentes nas demais colunas.

In [61]:
df_clean

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
0,Asia,China,118977.0,NaN,379053.0,503302,5272.0,1448471.400,160000.000,2026-01-22,05:00:13
1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,NaN,6.115,NaN,2026-01-22,05:00:12
2,South-America,Falkland-Islands,0.0,NaN,1930.0,1930,NaN,3.539,8.632,2026-01-22,05:00:12
3,North-America,Montserrat,19.0,NaN,1376.0,1403,8.0,4.965,17.762,2026-01-22,05:00:12
4,NaN,Diamond-Princess,0.0,NaN,699.0,712,13.0,NaN,NaN,2026-01-22,05:00:12
...,...,...,...,...,...,...,...,...,...,...,...
231,Europe,Europe,2550270.0,4453.0,248754104.0,253406198,2101824.0,NaN,NaN,2026-01-22,05:00:02
232,South-America,South-America,2149962.0,8953.0,66683585.0,70200879,1367332.0,NaN,NaN,2026-01-22,05:00:02
233,Oceania,Oceania,110368.0,31.0,14752388.0,14895771,33015.0,NaN,NaN,2026-01-22,05:00:02
234,Africa,Africa,511224.0,529.0,12090808.0,12860924,258892.0,NaN,NaN,2026-01-22,05:00:02
236,North-America,USA,786167.0,940.0,109814428.0,111820082,1219487.0,334805.269,1186851.502,2026-01-22,05:00:02

'test.total (k)' foi mantida no dataset. Mesmo que essa coluna tenha 15 valores ausente, estes foram mantidos, pois essa variável não é necessária para responder aos objetivos definidos para a análise e não há informação suficiente no dataset para inferir os valores ausentes de forma confiável.

In [62]:
df_clean.loc[
    df_clean['cases.recovered'].isna(),
    ['country', 'continent', 'cases.total',
     'cases.active', 'cases.recovered',
     'deaths.total', 'population(k)', 'test.total (k)']
]

,country,continent,cases.total,cases.active,cases.recovered,deaths.total,population(k),test.total (k)
10,St-Barth,North-America,5507,NaN,NaN,6.0,9.945,78.646
12,Tokelau,Oceania,80,80.0,NaN,NaN,1.378,NaN
14,Sierra-Leone,Africa,7779,NaN,NaN,126.0,8306.436,259.958
15,British-Virgin-Islands,North-America,7392,NaN,NaN,64.0,30.596,107.339
20,Anguilla,North-America,3904,NaN,NaN,12.0,15.230,51.382
22,Tuvalu,Oceania,2943,NaN,NaN,1.0,12.066,NaN
37,Monaco,Europe,17181,NaN,NaN,67.0,39.783,78.646
43,Saint-Martin,North-America,12324,NaN,NaN,63.0,39.730,112.382
47,Isle-of-Man,Europe,38008,NaN,NaN,116.0,85.732,150.753
58,Faeroe-Islands,Europe,34658,NaN,NaN,28.0,49.233,778.000
63,Micronesia,Oceania,26547,NaN,NaN,65.0,117.489,82.430
65,Solomon-Islands,Oceania,25954,NaN,NaN,199.0,721.159,NaN
67,Liechtenstein,Europe,21574,NaN,NaN,94.0,38.387,112.457
68,Gibraltar,Europe,20550,NaN,NaN,113.0,33.704,534.283
71,Mayotte,Africa,42027,NaN,NaN,188.0,286.259,176.919
76,Belize,North-America,71409,NaN,NaN,688.0,412.190,576.016
86,Andorra,Europe,48015,NaN,NaN,165.0,77.463,249.838
88,Tanzania,Africa,43223,NaN,NaN,846.0,63298.550,NaN
94,Suriname,South-America,82588,NaN,NaN,1408.0,596.831,242.207
95,Guadeloupe,North-America,203235,NaN,NaN,1021.0,399.794,938.039
102,Jamaica,North-America,156869,NaN,NaN,3756.0,2985.094,1183.986
110,Malawi,Africa,89535,NaN,NaN,2686.0,20180.839,624.784
113,New-Caledonia,Oceania,80064,NaN,NaN,314.0,290.915,98.964
114,French-Polynesia,Oceania,79254,NaN,NaN,650.0,284.164,NaN
117,R&eacute;union,Africa,494595,NaN,NaN,921.0,908.061,1603.660
118,Honduras,North-America,474590,NaN,NaN,11165.0,10221.247,1660.662
121,Oman,Asia,399449,NaN,NaN,4628.0,5323.993,25000.000
122,Luxembourg,Europe,391232,NaN,NaN,1232.0,642.371,4587.145
135,Martinique,North-America,230354,NaN,NaN,1102.0,374.087,828.928
136,Laos,Asia,218970,NaN,NaN,758.0,7481.023,1233.207
137,Iceland,Europe,209906,NaN,NaN,229.0,345.393,1996.384
146,Saudi-Arabia,Asia,841469,NaN,NaN,9646.0,35844.909,45481.735
147,Paraguay,South-America,837602,NaN,NaN,20155.0,7305.843,2657.506
153,Kuwait,Asia,667158,NaN,NaN,2570.0,4380.326,8455.743
155,Moldova,Europe,635145,NaN,NaN,12218.0,4013.171,3216.305
156,Estonia,Europe,628070,NaN,NaN,3001.0,1321.910,6968.103
162,Bangladesh,Asia,2049377,NaN,NaN,29493.0,167885.689,15254.399
164,Georgia,Asia,1861665,NaN,NaN,17132.0,3968.738,16920.079
174,Morocco,Africa,1278992,NaN,NaN,16303.0,37772.756,13001.033
176,Costa-Rica,North-America,1238883,NaN,NaN,9428.0,5182.354,4659.757
178,Tunisia,Africa,1153361,NaN,NaN,29423.0,12046.656,5013.383
181,UAE,Asia,1067030,NaN,NaN,2349.0,10081.785,200732.262
207,India,Asia,45035393,NaN,NaN,533570.0,1406631.776,935879.495
212,Japan,Asia,33803572,NaN,NaN,74694.0,125584.838,100414.883
216,Turkey,Asia,17232066,NaN,NaN,102174.0,85561.976,162743.369
223,Iran,Asia,7627186,NaN,NaN,146811.0,86022.837,57320.267
225,Poland,Europe,6661991,NaN,NaN,120598.0,37739.785,39323.709
227,Greece,Europe,6101379,NaN,NaN,37869.0,10316.637,102228.365

'cases.recovered': foram identificados 48 valores ausentes. Em todos esses registros, 'cases.active' também apresenta valor ausente, indicando um padrão de ausência conjunta dessas duas variáveis. Como não há informação suficiente para inferir os valores sem introduzir dados artificiais, os valores ausentes serão mantidos. A ausência não compromete os três objetivos principais da análise, que utilizam cases.total, population(k), continent, country e deaths.total.

In [63]:
df_clean.loc[
    df_clean['cases.active'].isna(),
    ['country', 'continent', 'cases.total',
     'cases.active', 'cases.recovered',
     'deaths.total', 'population(k)']
]

,country,continent,cases.total,cases.active,cases.recovered,deaths.total,population(k)
10,St-Barth,North-America,5507,NaN,NaN,6.0,9.945
14,Sierra-Leone,Africa,7779,NaN,NaN,126.0,8306.436
15,British-Virgin-Islands,North-America,7392,NaN,NaN,64.0,30.596
20,Anguilla,North-America,3904,NaN,NaN,12.0,15.230
22,Tuvalu,Oceania,2943,NaN,NaN,1.0,12.066
37,Monaco,Europe,17181,NaN,NaN,67.0,39.783
43,Saint-Martin,North-America,12324,NaN,NaN,63.0,39.730
47,Isle-of-Man,Europe,38008,NaN,NaN,116.0,85.732
58,Faeroe-Islands,Europe,34658,NaN,NaN,28.0,49.233
63,Micronesia,Oceania,26547,NaN,NaN,65.0,117.489
65,Solomon-Islands,Oceania,25954,NaN,NaN,199.0,721.159
67,Liechtenstein,Europe,21574,NaN,NaN,94.0,38.387
68,Gibraltar,Europe,20550,NaN,NaN,113.0,33.704
71,Mayotte,Africa,42027,NaN,NaN,188.0,286.259
76,Belize,North-America,71409,NaN,NaN,688.0,412.190
86,Andorra,Europe,48015,NaN,NaN,165.0,77.463
88,Tanzania,Africa,43223,NaN,NaN,846.0,63298.550
94,Suriname,South-America,82588,NaN,NaN,1408.0,596.831
95,Guadeloupe,North-America,203235,NaN,NaN,1021.0,399.794
102,Jamaica,North-America,156869,NaN,NaN,3756.0,2985.094
110,Malawi,Africa,89535,NaN,NaN,2686.0,20180.839
113,New-Caledonia,Oceania,80064,NaN,NaN,314.0,290.915
114,French-Polynesia,Oceania,79254,NaN,NaN,650.0,284.164
117,R&eacute;union,Africa,494595,NaN,NaN,921.0,908.061
118,Honduras,North-America,474590,NaN,NaN,11165.0,10221.247
121,Oman,Asia,399449,NaN,NaN,4628.0,5323.993
122,Luxembourg,Europe,391232,NaN,NaN,1232.0,642.371
135,Martinique,North-America,230354,NaN,NaN,1102.0,374.087
136,Laos,Asia,218970,NaN,NaN,758.0,7481.023
137,Iceland,Europe,209906,NaN,NaN,229.0,345.393
146,Saudi-Arabia,Asia,841469,NaN,NaN,9646.0,35844.909
147,Paraguay,South-America,837602,NaN,NaN,20155.0,7305.843
153,Kuwait,Asia,667158,NaN,NaN,2570.0,4380.326
155,Moldova,Europe,635145,NaN,NaN,12218.0,4013.171
156,Estonia,Europe,628070,NaN,NaN,3001.0,1321.910
162,Bangladesh,Asia,2049377,NaN,NaN,29493.0,167885.689
164,Georgia,Asia,1861665,NaN,NaN,17132.0,3968.738
174,Morocco,Africa,1278992,NaN,NaN,16303.0,37772.756
176,Costa-Rica,North-America,1238883,NaN,NaN,9428.0,5182.354
178,Tunisia,Africa,1153361,NaN,NaN,29423.0,12046.656
181,UAE,Asia,1067030,NaN,NaN,2349.0,10081.785
207,India,Asia,45035393,NaN,NaN,533570.0,1406631.776
212,Japan,Asia,33803572,NaN,NaN,74694.0,125584.838
216,Turkey,Asia,17232066,NaN,NaN,102174.0,85561.976
223,Iran,Asia,7627186,NaN,NaN,146811.0,86022.837
225,Poland,Europe,6661991,NaN,NaN,120598.0,37739.785
227,Greece,Europe,6101379,NaN,NaN,37869.0,10316.637

In [64]:
df_clean['cases.active'].isna().sum()

np.int64(47)

'cases.active': foram identificados 47 valores ausentes. Em todos esses registros, 'cases.recoveded' também apresenta valor ausente, indicando um padrão de ausência conjunta dessas duas variáveis. Como não há informação suficiente para inferir os valores sem introduzir dados artificiais, os valores ausentes serão mantidos. A ausência não compromete os três objetivos principais da análise, que utilizam cases.total, population(k), continent, country e deaths.total.

Validação final do dataset limpo

In [65]:
import pandas as pd

df_check = pd.read_csv('data/covid19_clean.csv')

df_check.shape

(227, 11)

Primeiras linhas Conferidas

In [66]:
df_check.head()

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
0,Asia,China,118977.0,NaN,379053.0,503302,5272.0,1448471.400,160000.000,2026-01-22,05:00:13
1,Africa,Saint-Helena,2164.0,NaN,2.0,2166,0.0,6.115,NaN,2026-01-22,05:00:12
2,South-America,Falkland-Islands,0.0,NaN,1930.0,1930,0.0,3.539,8.632,2026-01-22,05:00:12
3,North-America,Montserrat,19.0,NaN,1376.0,1403,8.0,4.965,17.762,2026-01-22,05:00:12
4,Africa,Western-Sahara,0.0,NaN,9.0,10,1.0,626.161,NaN,2026-01-22,05:00:12

Nulos verificados

In [67]:
df_check.isna().sum()

continent            0
country              0
cases.active        47
cases.critical     176
cases.recovered     48
cases.total          0
deaths.total         0
population(k)        0
test.total (k)      15
date                 0
time_hms             0
dtype: int64

Tipos de dados Verificados

In [77]:
df_check.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   continent        227 non-null    str
 1   country          227 non-null    str
 2   cases.active     180 non-null    float64
 3   cases.critical   51 non-null     float64
 4   cases.recovered  179 non-null    float64
 5   cases.total      227 non-null    int64
 6   deaths.total     227 non-null    float64
 7   population(k)    227 non-null    float64
 8   test.total (k)   212 non-null    float64
 9   date             227 non-null    str
 10  time_hms         227 non-null    str
dtypes: float64(6), int64(1), str(4)
memory usage: 19.6 KB

In [78]:
df_check.loc[
    df['deaths.total'].isna(),
    ['country', 'cases.total', 'cases.recovered',
     'cases.active', 'deaths.total']
]

             country  cases.total  cases.recovered  cases.active  deaths.total
1       Saint-Helena         2166              2.0        2164.0           0.0
2   Falkland-Islands         1930           1930.0           0.0           0.0
5              Nauru         5393           5347.0          45.0           1.0
12      Sierra-Leone         7779              NaN           NaN         126.0
23          Djibouti        15690          15427.0          74.0         189.0

death.total conferido

In [79]:
df_check['deaths.total'].isna().sum()

np.int64(0)

In [80]:
df_check.loc[
    df['population(k)'].isna(),
    ['country', 'continent', 'cases.total', 'deaths.total',
     'population(k)']
]

          country continent  cases.total  deaths.total  population(k)
4  Western-Sahara    Africa           10           1.0        626.161

population(k) conferido

In [81]:
df_check['population(k)'].isna().sum()

np.int64(0)

cases.active / cases.recovered conferidos

In [82]:
pd.crosstab(
    df['cases.active'].isna(),
    df['cases.recovered'].isna()
)

cases.recovered  False  True
cases.active
False              189      1
True                 0     47

Duplicatas verificadas

In [83]:
df_check.duplicated().sum()

np.int64(0)

In [84]:
df_check['country'].duplicated().sum()

np.int64(0)

Países/continentes inconsistentes conferidos

In [87]:
df_check[df_check['continent'] == df_check['country']][
    ['continent', 'country']
]

Empty DataFrame
Columns: [continent, country]
Index: []

Valores negativos verificados

In [90]:
df_check[
    (df_check['cases.total'] < 0) |
    (df_check['cases.active'] < 0) |
    (df_check['cases.critical'] < 0) |
    (df_check['cases.recovered'] < 0) |
    (df_check['deaths.total'] < 0) |
    (df_check['population(k)'] < 0) |
    (df_check['test.total (k)'] < 0)
]

Empty DataFrame
Columns: [continent, country, cases.active, cases.critical, cases.recovered, cases.total, deaths.total, population(k), test.total (k), date, time_hms]
Index: []

Estatísticas básicas verificadas

In [91]:
df_check.describe()

,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k)
count,1.800000e+02,51.000000,1.790000e+02,2.270000e+02,2.270000e+02,2.270000e+02,2.120000e+02
mean,3.363528e+04,52.647059,3.109801e+06,3.086681e+06,3.043203e+04,3.473206e+04,3.301750e+04
std,1.672248e+05,143.015918,1.034928e+07,1.010314e+07,1.100334e+05,1.392196e+05,1.201609e+05
min,0.000000e+00,1.000000,2.000000e+00,1.000000e+01,0.000000e+00,1.378000e+00,7.850000e+00
25%,4.575000e+01,3.500000,2.234900e+04,2.750350e+04,1.915000e+02,4.932080e+02,3.472967e+02
50%,6.025000e+02,11.000000,1.964060e+05,2.099060e+05,2.024000e+03,5.797805e+03,2.220024e+03
75%,5.842500e+03,23.500000,1.503542e+06,1.348198e+06,1.428700e+04,2.183934e+04,1.317852e+04
max,1.783377e+06,940.000000,1.098144e+08,1.118201e+08,1.219487e+06,1.448471e+06,1.186852e+06

Últimas linhas conferidas

In [92]:
df_check.tail()

,continent,country,cases.active,cases.critical,cases.recovered,cases.total,deaths.total,population(k),test.total (k),date,time_hms
222,Europe,Poland,NaN,NaN,NaN,6661991,120598.0,37739.785,39323.709,2026-01-22,05:00:03
223,South-America,Colombia,44821.0,342.0,6212152.0,6400173,143200.0,51512.762,36951.507,2026-01-22,05:00:03
224,Europe,Greece,NaN,NaN,NaN,6101379,37869.0,10316.637,102228.365,2026-01-22,05:00:03
225,Europe,Austria,3811.0,NaN,6054934.0,6081287,22542.0,9066.710,211273.524,2026-01-22,05:00:03
226,North-America,USA,786167.0,940.0,109814428.0,111820082,1219487.0,334805.269,1186851.502,2026-01-22,05:00:02

Tranformações

In [68]:
df_clean = df_clean.drop(index=[184, 229, 230, 231, 232, 233])

In [69]:
df_clean = df_clean.drop(index=[4])

In [70]:
df_clean = df_clean.drop(index=[5])

In [71]:
df_clean = df_clean.drop(index=[234])

In [72]:
df_clean.loc[df['country'].isin(['Saint-Helena','Falkland-Islands', 'Tokelau', 'Niue']), 'deaths.total'] = 0

In [73]:
df_clean.shape

(227, 11)

In [74]:
df_clean.to_csv('data/covid19_clean.csv', index=False)